CREATE TABLE team (
                      id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name          VARCHAR(100) NOT NULL,
                      contact_email VARCHAR(255) NOT NULL,
                      CONSTRAINT uq_team_name UNIQUE (name)
);

CREATE TABLE service_entry (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name        VARCHAR(100) NOT NULL,
                               description VARCHAR(1000),
                               status      VARCHAR(20)  NOT NULL,
                               environment VARCHAR(20)  NOT NULL,
                               base_url    VARCHAR(500),
                               repo_url    VARCHAR(500),
                               team_id     BIGINT       NOT NULL,
                               created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                               updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                               CONSTRAINT uq_service_entry_name UNIQUE (name),
                               CONSTRAINT fk_service_entry_team FOREIGN KEY (team_id) REFERENCES team (id),
                               CONSTRAINT ck_service_entry_status CHECK (status IN ('ACTIVE', 'DEPRECATED', 'RETIRED')),
                               CONSTRAINT ck_service_entry_environment CHECK (environment IN ('DEV', 'STAGING', 'PROD'))
);

CREATE INDEX idx_service_entry_team_id ON service_entry (team_id);
CREATE INDEX idx_service_entry_status ON service_entry (status);
CREATE INDEX idx_service_entry_environment ON service_entry (environment);